# Generated by Django 4.2 on 2024-03-04 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('sueldo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_gas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_luz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_comida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expensas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('alquiler', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('wifi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.mes')),
            ],
        ),
    ]
