# Generated by Django 5.0 on 2023-12-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('sueldo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bono_presencialidad', models.BooleanField(default=False)),
                ('gasto_gas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_luz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto_comida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
