# Generated by Django 3.2.5 on 2023-12-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mes',
            name='bono_presencialidad',
        ),
        migrations.AddField(
            model_name='mes',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
