# Generated by Django 3.2.5 on 2023-12-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20231211_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='alquiler',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='mes',
            name='expensas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
