# Generated by Django 3.2.5 on 2023-12-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20231219_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='expensas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
