# Generated by Django 3.2.5 on 2023-12-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_mes_expensas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='alquiler',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
